module.exports = [
    { id: 1, fullName: 'Oleh Lev', position: 'Web Dev', skill: 'PHP,JS', exp: 3, sex: 'Male', salary: 4500},
    { id: 2, fullName: 'John White', position: 'Web Dev', skill: 'PHP', exp: 1, sex: 'Male', salary: 1200},
    { id: 3, fullName: 'Jany Rad', position: 'Sale', skill: '-', exp: 2, sex: 'Famale', salary: 3500},
    { id: 4, fullName: 'Ivan Brown', position: 'iOS', skill: 'Swift', exp: 3, sex: 'Male', salary: 4000},
    { id: 5, fullName: 'Pet Bool', position: 'Android', skill: 'Java', exp: 2, sex: 'Male', salary: 3520},
    { id: 6, fullName: 'Emma Hallo', position: 'Android', skill: 'Kotlin', exp: 1, sex: 'Famale', salary: 2520},
    { id: 7, fullName: 'Olivia Jones', position: 'iOS', skill: 'Objective-C', exp: 3, sex: 'Famale', salary: 2820},
    { id: 8, fullName: 'William Smith', position: 'Designer', skill: 'Figma', exp: 5, sex: 'Male', salary: 3000},
    { id: 9, fullName: 'Oliver Alien', position: 'PM', skill: '-', exp: 4, sex: 'Male', salary: 6000},
    { id: 10, fullName: 'Mia Morris', position: 'Owner', skill: '-', exp: 10, sex: 'Famale', salary: 10000},
    { id: 11, fullName: 'Jeremy Clarkson', position: 'Driver', skill: '', exp: 5, sex: 'Male', salary: 2000},
    { id: 12, fullName: 'Samuel Faber', position: 'Web Dev', skill: '-', exp: 8, sex: 'Male', salary: 6000},
    { id: 13, fullName: 'Victoria Newton', position: 'Web Dev', skill: 'PHP, JS', exp: 7, sex: 'Famale', salary: 4200},
    { id: 14, fullName: 'Anastasia Willis', position: 'Android', skill: 'Kotlin', exp: 3, sex: 'Famale', salary: 3200},
    { id: 15, fullName: 'Lucas Archibald', position: 'Web Dev', skill: 'React', exp: 4, sex: 'Male', salary: 9000},
    { id: 16, fullName: 'Tyler Franklin', position: 'Owner', skill: '-', exp: 10, sex: 'Male', salary: 10000},
    { id: 17, fullName: 'Victoria Franklin', position: 'Driver', skill: '', exp: 5, sex: 'Famale', salary: 2000},
    { id: 18, fullName: 'Amanda Eddington', position: 'Web Dev', skill: '-', exp: 8, sex: 'Famale', salary: 6000},
    { id: 19, fullName: 'Ann Newton', position: 'Web Dev', skill: 'PHP, JS', exp: 7, sex: 'Famale', salary: 4150},
    { id: 20, fullName: 'Angel Hawkins', position: 'Android', skill: 'Kotlin', exp: 3, sex: 'Famale', salary: 4200},
    { id: 21, fullName: 'Jonathan Bond', position: 'Web Dev', skill: 'React', exp: 4, sex: 'Male', salary: 8000},
    { id: 22, fullName: 'Anthony Bach', position: 'iOS', skill: 'Objective-C', exp: 3, sex: 'Male', salary: 2820},
    { id: 23, fullName: 'Benjamin Creighton', position: 'Designer', skill: 'Figma', exp: 5, sex: 'Male', salary: 3000},
    { id: 24, fullName: 'Julian Obama', position: 'PM', skill: '-', exp: 4, sex: '', salary: 5436},
    { id: 25, fullName: 'Angelina Travolta', position: 'Owner', skill: '-', exp: 10, sex: 'Famale', salary: 6999},
    { id: 26, fullName: 'Timothy Willis', position: 'Owner', skill: '', exp: 5, sex: 'Male', salary: 9080},
    { id: 27, fullName: 'Charles Bach', position: 'Web Dev', skill: '-', exp: 8, sex: 'Male', salary: 6600},
    { id: 28, fullName: 'Mason Donaldson', position: 'Web Dev', skill: 'PHP, JS', exp: 7, sex: 'Male', salary: 4700},
    { id: 29, fullName: 'Maria Roberts', position: 'Web Dev', skill: 'PHP,JS', exp: 3, sex: 'Famale', salary: 4700},
    { id: 30, fullName: 'David Goodman', position: 'Web Dev', skill: 'PHP', exp: 1, sex: 'Male', salary: 1100},
    { id: 31, fullName: 'Benjamin Creighton', position: 'Sale', skill: '-', exp: 2, sex: 'Male', salary: 4500},
    { id: 32, fullName: 'James Travolta', position: 'iOS', skill: 'Swift', exp: 3, sex: 'Male', salary: 2000},
    { id: 33, fullName: 'Charles Willis', position: 'Android', skill: 'Java', exp: 2, sex: 'Male', salary: 3620},
    { id: 34, fullName: 'Nicholas Gilbert', position: 'Android', skill: 'Kotlin', exp: 1, sex: 'Male', salary: 2820},
    { id: 35, fullName: 'Jonathan Bond', position: 'iOS', skill: 'Objective-C', exp: 3, sex: 'Male', salary: 2220},
    { id: 36, fullName: 'Logan Franklin', position: 'Designer', skill: 'Figma', exp: 5, sex: 'Male', salary: 3090},
    { id: 37, fullName: 'Carlos Fisher', position: 'PM', skill: '-', exp: 4, sex: 'Male', salary: 6600},
    { id: 38, fullName: 'Tyler Gill', position: 'Owner', skill: '-', exp: 10, sex: 'Male', salary: 9200},
];
